Repository Nosto/nosto-shopware, pull requests merged in 2019-04, with the labels that each got.

#217 Bumped the copyright year
  .phan/Shopware/Models/Attribute/Customer.php
  .phan/Shopware/Models/Attribute/Order.php
  Bootstrap.php
  Components/Account.php
  Components/Customer.php
  Components/Helper/CartRestore.php
  Components/Helper/Currency.php
  Components/Helper/CustomFields.php
  Components/Helper/Customer.php
  Components/Helper/Email.php
  Components/Helper/ExchangeRates.php
  Components/Helper/Image.php
  Components/Helper/Price.php
  Components/Helper/Tag.php
  Components/Meta/Account.php
  Components/Meta/Account/Iframe.php
  Components/Meta/Account/Owner.php
  Components/Meta/Oauth.php
  Components/Model/Base.php
  Components/Model/Cart.php
  Components/Model/Cart/LineItem.php
  Components/Model/Category.php
  Components/Model/Customer.php
  Components/Model/Order.php
  Components/Model/Order/Buyer.php
  Components/Model/Order/LineItem.php
  Components/Model/Order/Status.php
  Components/Model/Product.php
  Components/Model/Repository/ProductStreams.php
  Components/Model/Sku.php
  Components/Operation/ExchangeRates.php
  Components/Operation/Product.php
  Components/Operation/Settings.php
  Components/Order/Confirmation.php
  Components/Url.php
  Components/User/Builder.php
  Controllers/backend/NostoTagging.php
  Controllers/frontend/NostoTagging.php
  Models/Account/Repository.php
  Models/Nosto/Account/Account.php
  Models/Nosto/Account/Repository.php
  Models/Nosto/Customer/Customer.php
  Models/Nosto/Customer/Repository.php
  Models/Nosto/Setting/Repository.php
  Models/Nosto/Setting/Setting.php
  Models/Order/Repository.php
  Models/Product/Repository.php
  Views/backend/nosto_start_app/menu.js
  Views/backend/nosto_tagging/app.js
  Views/backend/nosto_tagging/controller/main.js
  Views/backend/nosto_tagging/model/account.js
  Views/backend/nosto_tagging/store/account.js
  Views/backend/nosto_tagging/view/main.js
  build.xml
  phan.php
  ruleset.xml
Labels: Refactoring

#219 Feature - Bump SDK to auto escape all product tagging
  Bootstrap.php
  CHANGELOG.md
  composer.json
  composer.lock
Labels: enhancement

#222 Hotfix - 2.4.1 - Add nullcheck to cart line item
  Bootstrap.php
  CHANGELOG.md
  Components/Model/Cart/LineItem.php
  composer.json
Labels: bug
